#include <stdio.h>
#include <string.h>
#include <time.h>
#include "../headers/admin.h"
#include "../headers/users.h"
#include "../headers/structures.h"
#include "../headers/inventory.h"
#include "../headers/helper.h"

static void getCurrentDateTime(char dateTime[]);
static FILE *openPatientFile(void);
static void skipHeaderLine(FILE *file);
static int readPatient(FILE *file, Patient *patient);
static void printPatientTableHeader(void);
static void printPatientRow(Patient patient);
static void printPatientDetails(Patient patient);
static void printPatientReportHeader(char title[], char currentUserName[], char dateTime[]);
static void waitForEnter(void);
static int readMenuChoice(int min, int max);
static int chooseGenderFilter(char selectedGender[]);
static int chooseAgeRange(char ageLabel[], int *minAge, int *maxAge);

/// Gets the current date and time for reports.
static void getCurrentDateTime(char dateTime[])
{
    time_t t = time(NULL);
    struct tm *currentTime = localtime(&t);

    strftime(dateTime, 50, "%Y-%m-%d %H:%M:%S", currentTime);
}

/// Opens the patient file and shows an error if it cannot open.
static FILE *openPatientFile(void)
{
    FILE *file = fopen("data/patients.txt", "r");

    if (file == NULL)
    {
        printf("Error opening patients file.\n");
    }

    return file;
}

/// Skips the first line of a text file.
static void skipHeaderLine(FILE *file)
{
    fscanf(file, "%*[^\n]\n");
}

/// Reads one patient record from the file.
static int readPatient(FILE *file, Patient *patient)
{
    return fscanf(file, " %14[^|]|%49[^|]|%d|%9[^|]|%19[^\n]\n",
                  patient->patient_id,
                  patient->name,
                  &patient->age,
                  patient->gender,
                  patient->contact) == 5;
}

/// Prints the patient table heading used in reports.
static void printPatientTableHeader(void)
{
    printf("--------------------------------------------------------------\n");
    printf("%-12s %-15s %-5s %-10s %-15s\n",
           "PatientID", "Name", "Age", "Gender", "Contact");
    printf("--------------------------------------------------------------\n");
}

/// Prints one patient in table format.
static void printPatientRow(Patient patient)
{
    printf("%-12s %-15s %-5d %-10s %-15s\n",
           patient.patient_id,
           patient.name,
           patient.age,
           patient.gender,
           patient.contact);
}

/// Prints one patient's details in a simple list format.
static void printPatientDetails(Patient patient)
{
    printf("Patient ID : %s\n", patient.patient_id);
    printf("Name       : %s\n", patient.name);
    printf("Age        : %d\n", patient.age);
    printf("Gender     : %s\n", patient.gender);
    printf("Contact    : %s\n", patient.contact);
}

/// Prints the common header for patient reports.
static void printPatientReportHeader(char title[], char currentUserName[], char dateTime[])
{
    printf("\n=====================================\n");
    printf("%s\n", title);
    printf("=====================================\n");
    printf("Report generated by %s at %s\n", currentUserName, dateTime);
}

/// Waits for the user to press Enter.
static void waitForEnter(void)
{
    printf("\nPress Enter to go back...");
    getchar();
}

/// Reads a menu choice and keeps asking until it is valid.
static int readMenuChoice(int min, int max)
{
    int choice;

    while (1)
    {
        if (scanf("%d", &choice) != 1)
        {
            printf("Invalid input. Please enter %d-%d.\n", min, max);
            while (getchar() != '\n');
            printf("Enter your choice: ");
            continue;
        }

        while (getchar() != '\n');

        if (choice >= min && choice <= max)
        {
            return choice;
        }

        printf("Invalid input. Please enter %d-%d.\n", min, max);
        printf("Enter your choice: ");
    }
}

/// Lets the admin choose a gender filter.
static int chooseGenderFilter(char selectedGender[])
{
    int choice;

    while (1)
    {
        printf("\n=====================================\n");
        printf("         FILTER BY GENDER            \n");
        printf("=====================================\n");
        printf("1. Female\n");
        printf("2. Male\n");
        printf("0. Go Back\n");
        printf("Enter your choice: ");

        choice = readMenuChoice(0, 2);

        if (choice == 0)
        {
            return 0;
        }

        if (choice == 1)
        {
            strcpy(selectedGender, "Female");
        }
        else
        {
            strcpy(selectedGender, "Male");
        }

        return 1;
    }
}

/// Lets the admin choose an age range filter.
static int chooseAgeRange(char ageLabel[], int *minAge, int *maxAge)
{
    int choice;

    while (1)
    {
        printf("\n=====================================\n");
        printf("        FILTER BY AGE RANGE          \n");
        printf("=====================================\n");
        printf("1. Children (0 - 12)\n");
        printf("2. Teenagers (13 - 19)\n");
        printf("3. Young Adult (20 - 35)\n");
        printf("4. Adult (36 - 64)\n");
        printf("5. Senior (65+)\n");
        printf("0. Go Back\n");
        printf("Enter your choice: ");

        choice = readMenuChoice(0, 5);

        if (choice == 0)
        {
            return 0;
        }

        if (choice == 1)
        {
            *minAge = 0;
            *maxAge = 12;
            strcpy(ageLabel, "Children");
        }
        else if (choice == 2)
        {
            *minAge = 13;
            *maxAge = 19;
            strcpy(ageLabel, "Teenagers");
        }
        else if (choice == 3)
        {
            *minAge = 20;
            *maxAge = 35;
            strcpy(ageLabel, "Young Adult");
        }
        else if (choice == 4)
        {
            *minAge = 36;
            *maxAge = 64;
            strcpy(ageLabel, "Adult");
        }
        else
        {
            *minAge = 65;
            *maxAge = 200;
            strcpy(ageLabel, "Senior");
        }

        return 1;
    }
}

/// Shows the patient report menu.
void patientReportMenu(char currentUserName[])
{
    int choice;

    while (1)
    {
        printf("\n=====================================\n");
        printf("            PATIENT REPORT           \n");
        printf("=====================================\n");
        printf("1. View Patient Report\n");
        printf("2. Search Patient\n");
        printf("3. Filter Patient\n");
        printf("0. Go Back\n");
        printf("Enter your choice: ");

        choice = readMenuChoice(0, 3);

        if (choice == 1)
        {
            viewPatients(currentUserName);
        }
        else if (choice == 2)
        {
            searchPatient(currentUserName);
        }
        else if (choice == 3)
        {
            filterPatientsMenu(currentUserName);
        }
        else
        {
            printf("Going back...\n");
            return;
        }
    }
}

/// Shows the patient filter menu.
void filterPatientsMenu(char currentUserName[])
{
    int choice;

    while (1)
    {
        printf("\n=====================================\n");
        printf("           FILTER PATIENTS           \n");
        printf("=====================================\n");
        printf("1. Filter by Gender\n");
        printf("2. Filter by Age Range\n");
        printf("0. Go Back\n");
        printf("Enter your choice: ");

        choice = readMenuChoice(0, 2);

        if (choice == 1)
        {
            filterByGender(currentUserName);
        }
        else if (choice == 2)
        {
            filterByAgeRange(currentUserName);
        }
        else
        {
            printf("Going back...\n");
            return;
        }
    }
}

/// Filters patients by gender and prints the report.
void filterByGender(char currentUserName[])
{
    FILE *file;
    Patient patient;
    char selectedGender[10];
    char dateTime[50];
    int found = 0;

    if (!chooseGenderFilter(selectedGender))
    {
        return;
    }

    file = openPatientFile();
    if (file == NULL)
    {
        return;
    }

    getCurrentDateTime(dateTime);
    printPatientReportHeader("        FILTERED PATIENT REPORT      ", currentUserName, dateTime);
    printf("Filtered By Gender: %s\n", selectedGender);
    printPatientTableHeader();

    skipHeaderLine(file);

    while (readPatient(file, &patient))
    {
        if (strcmp(selectedGender, patient.gender) == 0)
        {
            printPatientRow(patient);
            found = 1;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("No matching patient found.\n");
    }

    waitForEnter();
}

/// Filters patients by age range and prints the report.
void filterByAgeRange(char currentUserName[])
{
    FILE *file;
    Patient patient;
    char ageLabel[20];
    char dateTime[50];
    int minAge;
    int maxAge;
    int found = 0;

    if (!chooseAgeRange(ageLabel, &minAge, &maxAge))
    {
        return;
    }

    file = openPatientFile();
    if (file == NULL)
    {
        return;
    }

    getCurrentDateTime(dateTime);
    printPatientReportHeader("        FILTERED PATIENT REPORT      ", currentUserName, dateTime);
    printf("Filtered By Age Category: %s\n", ageLabel);
    printPatientTableHeader();

    skipHeaderLine(file);

    while (readPatient(file, &patient))
    {
        if (patient.age >= minAge && patient.age <= maxAge)
        {
            printPatientRow(patient);
            found = 1;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("No matching patient found.\n");
    }

    waitForEnter();
}

/// Shows the patient search menu.
void searchPatient(char currentUserName[])
{
    int choice;

    while (1)
    {
        printf("\n=====================================\n");
        printf("           SEARCH PATIENT            \n");
        printf("=====================================\n");
        printf("1. Search by Patient ID\n");
        printf("2. Search by Patient Name\n");
        printf("0. Go Back\n");
        printf("Enter your choice: ");

        choice = readMenuChoice(0, 2);

        if (choice == 1)
        {
            searchPatientByID(currentUserName);
        }
        else if (choice == 2)
        {
            searchPatientByName(currentUserName);
        }
        else
        {
            printf("Going back...\n");
            return;
        }
    }
}

/// Searches for a patient by patient ID.
void searchPatientByID(char currentUserName[])
{
    FILE *file = openPatientFile();
    Patient patient;
    char searchID[15];
    char dateTime[50];
    int found = 0;

    if (file == NULL)
    {
        return;
    }

    printf("Enter Patient ID: ");
    scanf(" %14[^\n]", searchID);
    while (getchar() != '\n');

    skipHeaderLine(file);

    while (readPatient(file, &patient))
    {
        if (strcmp(searchID, patient.patient_id) == 0)
        {
            getCurrentDateTime(dateTime);
            printPatientReportHeader("           PATIENT FOUND             ", currentUserName, dateTime);
            printf("Search By Patient ID: %s\n", searchID);
            printf("--------------------------------------------------\n");
            printPatientDetails(patient);
            found = 1;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("Patient not found.\n");
    }

    waitForEnter();
}

/// Searches for a patient by patient name.
void searchPatientByName(char currentUserName[])
{
    FILE *file = openPatientFile();
    Patient patient;
    char searchName[50];
    char patientNameLower[50];
    char dateTime[50];
    int found = 0;

    if (file == NULL)
    {
        return;
    }

    printf("Enter Patient Name: ");
    scanf(" %49[^\n]", searchName);
    while (getchar() != '\n');

    toLowerCase(searchName);
    skipHeaderLine(file);

    while (readPatient(file, &patient))
    {
        strcpy(patientNameLower, patient.name);
        toLowerCase(patientNameLower);

        if (strcmp(searchName, patientNameLower) == 0)
        {
            getCurrentDateTime(dateTime);
            printPatientReportHeader("           PATIENT FOUND             ", currentUserName, dateTime);
            printf("Search By Patient Name: %s\n", searchName);
            printf("--------------------------------------------------\n");
            printPatientDetails(patient);
            found = 1;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("Patient not found.\n");
    }

    waitForEnter();
}

/// Shows all patients in report format.
void viewPatients(char currentUserName[])
{
    FILE *file = openPatientFile();
    Patient patient;
    char dateTime[50];

    if (file == NULL)
    {
        return;
    }

    getCurrentDateTime(dateTime);
    printPatientReportHeader("           PATIENT REPORT            ", currentUserName, dateTime);
    printPatientTableHeader();

    skipHeaderLine(file);

    while (readPatient(file, &patient))
    {
        printPatientRow(patient);
    }

    fclose(file);
    waitForEnter();
}

/// Shows the main admin menu.
void adminMenu(char currentUserName[])
{
    int choice;

    while (1)
    {
        printf("\n=====================================\n");
        printf("              ADMIN MENU             \n");
        printf("=====================================\n");
        printf("1. Manage Users\n");
        printf("2. Manage Patient\n");
        printf("3. Manage Inventory\n");
        printf("0. Go Back\n");
        printf("Enter your choice: ");

        choice = readMenuChoice(0, 3);

        if (choice == 1)
        {
            manageUsersMenu(currentUserName);
        }
        else if (choice == 2)
        {
            patientReportMenu(currentUserName);
        }
        else if (choice == 3)
        {
            manageInventoryMenu(currentUserName);
        }
        else
        {
            printf("Going back...\n");
            return;
        }
    }
}






