#include <stdio.h>
#include <string.h>
#include <time.h>
#include "../headers/inventory.h"
#include "../headers/structures.h"
#include "../headers/helper.h"

FILE *openInventoryFile(void)
{
    FILE *file = fopen("data/inventory.txt", "r");

    if (file == NULL)
    {
        printf("Error opening inventory file.\n");
    }

    return file;
}

int readInventory(FILE *file, Inventory *inv)
{
    return fscanf(file, " %9[^|]|%49[^|]|%29[^|]|%d",
                  inv->item_id, inv->item_name, inv->category, &inv->stock_level) == 4;
}

void skipInventoryHeader(FILE *file)
{
    fscanf(file, "%*[^\n]\n");
}

void printInventoryTableHeader(void)
{
    printf("------------------------------------------------------------\n");
    printf("%-8s %-20s %-12s %-8s\n", "ItemID", "ItemName", "Category", "Stock");
    printf("------------------------------------------------------------\n");
}

void printInventoryRow(Inventory inv)
{
    printf("%-8s %-20s %-12s %-8d\n",
           inv.item_id, inv.item_name, inv.category, inv.stock_level);
}

void printInventoryDetails(Inventory inv)
{
    printf("\nItem Found:\n");
    printf("Item ID     : %s\n", inv.item_id);
    printf("Item Name   : %s\n", inv.item_name);
    printf("Category    : %s\n", inv.category);
    printf("Stock Level : %d\n", inv.stock_level);
}

void waitForInventoryEnter(void)
{
    printf("\nPress Enter to go back...");
    getchar();
}

void getInventoryReportDateTime(char dateTime[])
{
    time_t t = time(NULL);
    struct tm *currentTime = localtime(&t);

    strftime(dateTime, 50, "%Y-%m-%d %H:%M:%S", currentTime);
}

void printInventoryReportHeader(char title[], char currentUserName[])
{
    char dateTime[50];

    getInventoryReportDateTime(dateTime);

    printf("\n=====================================\n");
    printf("%s\n", title);
    printf("=====================================\n");
    printf("Report generated by %s at %s\n", currentUserName, dateTime);
}

int readInventoryMenuChoice(int min, int max)
{
    int choice;

    while (1)
    {
        if (scanf("%d", &choice) != 1)
        {
            printf("Invalid input. Please enter %d-%d.\n", min, max);
            while (getchar() != '\n');
            printf("Enter your choice: ");
            continue;
        }

        while (getchar() != '\n');

        if (choice >= min && choice <= max)
        {
            return choice;
        }

        printf("Invalid input. Please enter %d-%d.\n", min, max);
        printf("Enter your choice: ");
    }
}

int isSameItemName(char firstName[], char secondName[])
{
    char firstLower[50];
    char secondLower[50];

    strcpy(firstLower, firstName);
    strcpy(secondLower, secondName);
    toLowerCase(firstLower);
    toLowerCase(secondLower);

    return strcmp(firstLower, secondLower) == 0;
}

int chooseStockLevel(char stockLabel[], int *minStock, int *maxStock)
{
    int choice;

    while (1)
    {
        printf("\nChoose Stock Level:\n");
        printf("1. Out of Stock (0)\n");
        printf("2. Low Stock (1-20)\n");
        printf("3. Stable (21-100)\n");
        printf("4. Surplus (more than 100)\n");
        printf("Enter choice: ");

        choice = readInventoryMenuChoice(1, 4);

        if (choice == 1)
        {
            *minStock = 0;
            *maxStock = 0;
            strcpy(stockLabel, "Out of Stock");
        }
        else if (choice == 2)
        {
            *minStock = 1;
            *maxStock = 20;
            strcpy(stockLabel, "Low Stock");
        }
        else if (choice == 3)
        {
            *minStock = 21;
            *maxStock = 100;
            strcpy(stockLabel, "Stable");
        }
        else
        {
            *minStock = 101;
            *maxStock = 2147483647;
            strcpy(stockLabel, "Surplus");
        }

        return 1;
    }
}

int chooseInventoryCategory(char category[])
{
    int categoryChoice;

    while (1)
    {
        printf("\nChoose Category:\n");
        printf("1. Medication\n");
        printf("2. Supplies\n");
        printf("3. Equipment\n");
        printf("Enter choice: ");

        categoryChoice = readInventoryMenuChoice(1, 3);

        if (categoryChoice == 1)
        {
            strcpy(category, "Medication");
        }
        else if (categoryChoice == 2)
        {
            strcpy(category, "Supplies");
        }
        else
        {
            strcpy(category, "Equipment");
        }

        return categoryChoice;
    }
}

void manageInventoryMenu(char currentUserName[])
{
    int choice;

    while (1)
    {
        printf("\n=====================================\n");
        printf("          MANAGE INVENTORY           \n");
        printf("=====================================\n");
        printf("1. View Inventory Report\n");
        printf("2. Search Inventory\n");
        printf("3. Filter Inventory\n");
        printf("0. Go Back\n");
        printf("Enter your choice: ");

        choice = readInventoryMenuChoice(0, 3);

        if (choice == 1)
        {
            viewInventoryReport(currentUserName);
        }
        else if (choice == 2)
        {
            searchInventory();
        }
        else if (choice == 3)
        {
            filterInventory(currentUserName);
        }
        else
        {
            return;
        }
    }
}

void viewInventory(void)
{
    FILE *file = openInventoryFile();
    Inventory inv;

    if (file == NULL)
    {
        return;
    }

    printf("\n=====================================\n");
    printf("           VIEW INVENTORY            \n");
    printf("=====================================\n");
    printInventoryTableHeader();

    skipInventoryHeader(file);

    while (readInventory(file, &inv))
    {
        printInventoryRow(inv);
    }

    fclose(file);
    waitForInventoryEnter();
}

void viewInventoryReport(char currentUserName[])
{
    FILE *file = openInventoryFile();
    Inventory inv;

    if (file == NULL)
    {
        return;
    }

    printInventoryReportHeader("        INVENTORY REPORT             ", currentUserName);
    printInventoryTableHeader();

    skipInventoryHeader(file);

    while (readInventory(file, &inv))
    {
        printInventoryRow(inv);
    }

    fclose(file);
    waitForInventoryEnter();
}

void searchInventory(void)
{
    printf("\n=====================================\n");
    printf("           SEARCH INVENTORY          \n");
    printf("=====================================\n");

    searchInventoryByID();
}

void searchInventoryByID(void)
{
    FILE *file = openInventoryFile();
    Inventory inv;
    char searchID[10];
    char itemIdLower[10];
    int found = 0;

    if (file == NULL)
    {
        return;
    }

    printf("\nEnter Item ID: ");
    scanf(" %9[^\n]", searchID);
    while (getchar() != '\n');

    toLowerCase(searchID);
    skipInventoryHeader(file);

    while (readInventory(file, &inv))
    {
        strcpy(itemIdLower, inv.item_id);
        toLowerCase(itemIdLower);

        if (strcmp(searchID, itemIdLower) == 0)
        {
            printInventoryDetails(inv);
            found = 1;
            break;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("Item not found.\n");
    }

    waitForInventoryEnter();
}

void searchInventoryByName(void)
{
    FILE *file = openInventoryFile();
    Inventory inv;
    char searchName[50];
    int found = 0;

    if (file == NULL)
    {
        return;
    }

    printf("\nEnter Item Name: ");
    scanf(" %49[^\n]", searchName);
    while (getchar() != '\n');

    skipInventoryHeader(file);

    while (readInventory(file, &inv))
    {
        if (isSameItemName(searchName, inv.item_name))
        {
            printInventoryDetails(inv);
            found = 1;
            break;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("Item not found.\n");
    }

    waitForInventoryEnter();
}

void filterInventory(char currentUserName[])
{
    int choice;

    while (1)
    {
        printf("\n=====================================\n");
        printf("           FILTER INVENTORY          \n");
        printf("=====================================\n");
        printf("1. Filter By Item Name\n");
        printf("2. Filter By Item Category\n");
        printf("3. Filter By Stock Level\n");
        printf("0. Go Back\n");
        printf("Enter your choice: ");

        choice = readInventoryMenuChoice(0, 3);

        if (choice == 1)
        {
            filterInventoryByName(currentUserName);
        }
        else if (choice == 2)
        {
            filterInventoryByCategory(currentUserName);
        }
        else if (choice == 3)
        {
            filterInventoryByStockLevel(currentUserName);
        }
        else
        {
            return;
        }
    }
}

void filterInventoryByName(char currentUserName[])
{
    FILE *file = openInventoryFile();
    Inventory inv;
    char searchName[50];
    int found = 0;

    if (file == NULL)
    {
        return;
    }

    printf("\nEnter Item Name: ");
    scanf(" %49[^\n]", searchName);
    while (getchar() != '\n');

    printInventoryReportHeader("       FILTERED INVENTORY REPORT     ", currentUserName);
    printf("Filtered By Item Name: %s\n", searchName);
    printInventoryTableHeader();

    skipInventoryHeader(file);

    while (readInventory(file, &inv))
    {
        if (isSameItemName(searchName, inv.item_name))
        {
            printInventoryRow(inv);
            found = 1;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("No items found with this name.\n");
    }

    waitForInventoryEnter();
}

void filterInventoryByCategory(char currentUserName[])
{
    FILE *file = openInventoryFile();
    Inventory inv;
    char category[30];
    int found = 0;

    if (file == NULL)
    {
        return;
    }

    chooseInventoryCategory(category);

    printInventoryReportHeader("       FILTERED INVENTORY REPORT     ", currentUserName);
    printf("Filtered By Category: %s\n", category);
    printInventoryTableHeader();

    skipInventoryHeader(file);

    while (readInventory(file, &inv))
    {
        if (strcmp(inv.category, category) == 0)
        {
            printInventoryRow(inv);
            found = 1;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("No items found in this category.\n");
    }

    waitForInventoryEnter();
}

void filterInventoryByStockLevel(char currentUserName[])
{
    FILE *file = openInventoryFile();
    Inventory inv;
    char stockLabel[20];
    int minStock;
    int maxStock;
    int found = 0;

    if (file == NULL)
    {
        return;
    }

    chooseStockLevel(stockLabel, &minStock, &maxStock);

    printInventoryReportHeader("       FILTERED INVENTORY REPORT     ", currentUserName);
    printf("Filtered By Stock Level: %s\n", stockLabel);
    printInventoryTableHeader();

    skipInventoryHeader(file);

    while (readInventory(file, &inv))
    {
        if (inv.stock_level >= minStock && inv.stock_level <= maxStock)
        {
            printInventoryRow(inv);
            found = 1;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("No items found in this stock range.\n");
    }

    waitForInventoryEnter();
}
