#include <stdio.h>
#include <string.h>
#include <time.h>
#include "../headers/inventory.h"
#include "../headers/structures.h"
#include "../headers/helper.h"

static void printInventoryTableHeader(const char title[])
{
    printf("\n============================================================\n");
    printf("%28s\n", title);
    printf("============================================================\n");
    printf("%-8s %-20s %-12s %-8s\n", "ItemID", "ItemName", "Category", "Stock");
    printf("------------------------------------------------------------\n");
}

static void printInventoryRow(Inventory inv)
{
    printf("%-8s %-20s %-12s %-8d\n",
           inv.item_id, inv.item_name, inv.category, inv.stock_level);
}

static void printInventoryDetails(Inventory inv)
{
    printf("\nItem Found:\n");
    printf("Item ID     : %s\n", inv.item_id);
    printf("Item Name   : %s\n", inv.item_name);
    printf("Category    : %s\n", inv.category);
    printf("Stock Level : %d\n", inv.stock_level);
}

static void waitForEnter(void)
{
    printf("\nPress Enter to go back...");
    getchar();
}

static void getInventoryReportDateTime(char dateTime[])
{
    time_t t;
    struct tm *currentTime;

    t = time(NULL);
    currentTime = localtime(&t);

    strftime(dateTime, 50, "%Y-%m-%d %H:%M:%S", currentTime);
}

int chooseInventoryCategory(char category[])
{
    int categoryChoice;

    while (1)
    {
        printf("\nChoose Category:\n");
        printf("1. Medication\n");
        printf("2. Supplies\n");
        printf("3. Equipment\n");
        printf("Enter choice: ");

        if (scanf("%d", &categoryChoice) != 1)
        {
            printf("Invalid input. Please enter a value from 1 to 3.\n");
            while (getchar() != '\n');
            continue;
        }

        while (getchar() != '\n');

        if (categoryChoice == 1)
        {
            strcpy(category, "Medication");
            return categoryChoice;
        }
        else if (categoryChoice == 2)
        {
            strcpy(category, "Supplies");
            return categoryChoice;
        }
        else if (categoryChoice == 3)
        {
            strcpy(category, "Equipment");
            return categoryChoice;
        }

        printf("Invalid choice. Please try again.\n");
    }
}

void manageInventoryMenu(char currentUserName[])
{
    int choice;

    while (1)
    {
        printf("\n=====================================\n");
        printf("          MANAGE INVENTORY           \n");
        printf("=====================================\n");
        printf("1. View Inventory Report\n");
        printf("2. Search Inventory\n");
        printf("3. Filter Inventory\n");
        printf("0. Go Back\n");
        printf("Enter your choice: ");

        if (scanf("%d", &choice) != 1)
        {
            printf("Invalid input. Please enter 0-3.\n");
            while (getchar() != '\n');
            continue;
        }

        while (getchar() != '\n');

        if (choice == 1)
        {
            viewInventoryReport(currentUserName);
        }
        else if (choice == 2)
        {
            searchInventory();
        }
        else if (choice == 3)
        {
            filterInventory(currentUserName);
        }
        else if (choice == 0)
        {
            return;
        }
        else
        {
            printf("Invalid choice. Please enter 0-3.\n");
        }
    }
}

void viewInventory(void)
{
    FILE *file;
    Inventory inv;

    file = fopen("data/inventory.txt", "r");

    if (file == NULL)
    {
        printf("Error opening inventory file.\n");
        return;
    }

    printInventoryTableHeader("VIEW INVENTORY");

    fscanf(file, "%*[^\n]\n");

    while (fscanf(file, " %9[^|]|%49[^|]|%29[^|]|%d",
                  inv.item_id, inv.item_name, inv.category, &inv.stock_level) == 4)
    {
        printInventoryRow(inv);
    }

    fclose(file);
    waitForEnter();
}

void viewInventoryReport(char currentUserName[])
{
    FILE *file;
    Inventory inv;
    char dateTime[50];

    file = fopen("data/inventory.txt", "r");

    if (file == NULL)
    {
        printf("Error opening inventory file.\n");
        return;
    }

    getInventoryReportDateTime(dateTime);

    printf("\n=====================================\n");
    printf("        INVENTORY REPORT             \n");
    printf("=====================================\n");
    printf("Report generated by %s at %s\n", currentUserName, dateTime);
    printf("------------------------------------------------------------\n");
    printf("%-8s %-20s %-12s %-8s\n", "ItemID", "ItemName", "Category", "Stock");
    printf("------------------------------------------------------------\n");

    fscanf(file, "%*[^\n]\n");

    while (fscanf(file, " %9[^|]|%49[^|]|%29[^|]|%d",
                  inv.item_id, inv.item_name, inv.category, &inv.stock_level) == 4)
    {
        printInventoryRow(inv);
    }

    fclose(file);
    waitForEnter();
}

void searchInventory(void)
{
    int choice;

    while (1)
    {
        printf("\n=====================================\n");
        printf("           SEARCH INVENTORY          \n");
        printf("=====================================\n");
        printf("1. Search By Item ID\n");
        printf("2. Search By Item Name\n");
        printf("0. Go Back\n");
        printf("Enter your choice: ");

        if (scanf("%d", &choice) != 1)
        {
            printf("Invalid input. Please enter 0-2.\n");
            while (getchar() != '\n');
            continue;
        }

        while (getchar() != '\n');

        if (choice == 1)
        {
            searchInventoryByID();
        }
        else if (choice == 2)
        {
            searchInventoryByName();
        }
        else if (choice == 0)
        {
            return;
        }
        else
        {
            printf("Invalid choice. Please enter 0-2.\n");
        }
    }
}

void searchInventoryByID(void)
{
    FILE *file;
    Inventory inv;
    char searchID[10];
    char itemIdLower[10];
    int found;

    file = fopen("data/inventory.txt", "r");

    if (file == NULL)
    {
        printf("Error opening inventory file.\n");
        return;
    }

    found = 0;

    printf("\nEnter Item ID: ");
    scanf(" %9[^\n]", searchID);
    while (getchar() != '\n');

    toLowerCase(searchID);
    fscanf(file, "%*[^\n]\n");

    while (fscanf(file, " %9[^|]|%49[^|]|%29[^|]|%d",
                  inv.item_id, inv.item_name, inv.category, &inv.stock_level) == 4)
    {
        strcpy(itemIdLower, inv.item_id);
        toLowerCase(itemIdLower);

        if (strcmp(searchID, itemIdLower) == 0)
        {
            printInventoryDetails(inv);
            found = 1;
            break;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("Item not found.\n");
    }

    waitForEnter();
}

void searchInventoryByName(void)
{
    FILE *file;
    Inventory inv;
    char searchName[50];
    char itemNameLower[50];
    int found;

    file = fopen("data/inventory.txt", "r");

    if (file == NULL)
    {
        printf("Error opening inventory file.\n");
        return;
    }

    found = 0;

    printf("\nEnter Item Name: ");
    scanf(" %49[^\n]", searchName);
    while (getchar() != '\n');

    toLowerCase(searchName);
    fscanf(file, "%*[^\n]\n");

    while (fscanf(file, " %9[^|]|%49[^|]|%29[^|]|%d",
                  inv.item_id, inv.item_name, inv.category, &inv.stock_level) == 4)
    {
        strcpy(itemNameLower, inv.item_name);
        toLowerCase(itemNameLower);

        if (strcmp(searchName, itemNameLower) == 0)
        {
            printInventoryDetails(inv);
            found = 1;
            break;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("Item not found.\n");
    }

    waitForEnter();
}

void filterInventory(char currentUserName[])
{
    int choice;

    while (1)
    {
        printf("\n=====================================\n");
        printf("           FILTER INVENTORY          \n");
        printf("=====================================\n");
        printf("1. Filter By Item Category\n");
        printf("2. Filter By Stock Level\n");
        printf("0. Go Back\n");
        printf("Enter your choice: ");

        if (scanf("%d", &choice) != 1)
        {
            printf("Invalid input. Please enter 0-2.\n");
            while (getchar() != '\n');
            continue;
        }

        while (getchar() != '\n');

        if (choice == 1)
        {
            filterInventoryByCategory(currentUserName);
        }
        else if (choice == 2)
        {
            filterInventoryByStockLevel(currentUserName);
        }
        else if (choice == 0)
        {
            return;
        }
        else
        {
            printf("Invalid choice. Please enter 0-2.\n");
        }
    }
}

void filterInventoryByCategory(char currentUserName[])
{
    FILE *file;
    Inventory inv;
    char category[30];
    char dateTime[50];
    int found;

    file = fopen("data/inventory.txt", "r");

    if (file == NULL)
    {
        printf("Error opening inventory file.\n");
        return;
    }

    found = 0;
    chooseInventoryCategory(category);
    getInventoryReportDateTime(dateTime);

    printf("\n=====================================\n");
    printf("       FILTERED INVENTORY REPORT     \n");
    printf("=====================================\n");
    printf("Report generated by %s at %s\n", currentUserName, dateTime);
    printf("Filtered By Category: %s\n", category);
    printf("------------------------------------------------------------\n");
    printf("%-8s %-20s %-12s %-8s\n", "ItemID", "ItemName", "Category", "Stock");
    printf("------------------------------------------------------------\n");

    fscanf(file, "%*[^\n]\n");

    while (fscanf(file, " %9[^|]|%49[^|]|%29[^|]|%d",
                  inv.item_id, inv.item_name, inv.category, &inv.stock_level) == 4)
    {
        if (strcmp(inv.category, category) == 0)
        {
            printInventoryRow(inv);
            found = 1;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("No items found in this category.\n");
    }

    waitForEnter();
}

void filterInventoryByStockLevel(char currentUserName[])
{
    FILE *file;
    Inventory inv;
    char stockLabel[20];
    char dateTime[50];
    int choice;
    int minStock;
    int maxStock;
    int found;

    while (1)
    {
        printf("\nChoose Stock Level:\n");
        printf("1. Out of Stock (0)\n");
        printf("2. Low Stock (1-20)\n");
        printf("3. Stable (21-100)\n");
        printf("4. Surplus (more than 100)\n");
        printf("Enter choice: ");

        if (scanf("%d", &choice) != 1)
        {
            printf("Invalid input. Please enter 1-4.\n");
            while (getchar() != '\n');
            continue;
        }

        while (getchar() != '\n');

        if (choice == 1)
        {
            minStock = 0;
            maxStock = 0;
            strcpy(stockLabel, "Out of Stock");
            break;
        }
        else if (choice == 2)
        {
            minStock = 1;
            maxStock = 20;
            strcpy(stockLabel, "Low Stock");
            break;
        }
        else if (choice == 3)
        {
            minStock = 21;
            maxStock = 100;
            strcpy(stockLabel, "Stable");
            break;
        }
        else if (choice == 4)
        {
            minStock = 101;
            maxStock = 2147483647;
            strcpy(stockLabel, "Surplus");
            break;
        }

        printf("Invalid choice. Please enter 1-4.\n");
    }

    file = fopen("data/inventory.txt", "r");

    if (file == NULL)
    {
        printf("Error opening inventory file.\n");
        return;
    }

    found = 0;
    getInventoryReportDateTime(dateTime);

    printf("\n=====================================\n");
    printf("       FILTERED INVENTORY REPORT     \n");
    printf("=====================================\n");
    printf("Report generated by %s at %s\n", currentUserName, dateTime);
    printf("Filtered By Stock Level: %s\n", stockLabel);
    printf("------------------------------------------------------------\n");
    printf("%-8s %-20s %-12s %-8s\n", "ItemID", "ItemName", "Category", "Stock");
    printf("------------------------------------------------------------\n");

    fscanf(file, "%*[^\n]\n");

    while (fscanf(file, " %9[^|]|%49[^|]|%29[^|]|%d",
                  inv.item_id, inv.item_name, inv.category, &inv.stock_level) == 4)
    {
        if (inv.stock_level >= minStock && inv.stock_level <= maxStock)
        {
            printInventoryRow(inv);
            found = 1;
        }
    }

    fclose(file);

    if (found == 0)
    {
        printf("No items found in this stock range.\n");
    }

    waitForEnter();
}
